-- MySQL Script generated by MySQL Workbench
-- 01/18/15 22:53:39
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema termex
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `termex` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `termex` ;

-- -----------------------------------------------------
-- Table `termex`.`LANGUAGE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `termex`.`LANGUAGE` (
  `ID_LANG` INT NOT NULL AUTO_INCREMENT,
  `LANG_CODE` VARCHAR(5) NULL,
  `LANG_NAME` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_LANG`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `termex`.`CONTACT_US`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `termex`.`CONTACT_US` (
  `ID_CONT` INT NOT NULL AUTO_INCREMENT,
  `CONT_TITLE` VARCHAR(200) NULL,
  `CONT_EMAIL` VARCHAR(100) NULL,
  `CONT_CONTENT` VARCHAR(500) NULL,
  `CONT_CREATED_DATE` DATETIME NULL,
  PRIMARY KEY (`ID_CONT`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `termex`.`CATEGORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `termex`.`CATEGORY` (
  `ID_CAT` INT NOT NULL AUTO_INCREMENT,
  `CAT_CODE` VARCHAR(50) NULL,
  `CAT_STATUS` VARCHAR(1) NULL,
  PRIMARY KEY (`ID_CAT`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `termex`.`PRODUCT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `termex`.`PRODUCT` (
  `ID_PROD` INT NOT NULL AUTO_INCREMENT,
  `ID_CAT` INT NULL,
  `PROD_CODE` VARCHAR(45) NULL,
  `PROD_IMAGE` MEDIUMBLOB NULL,
  `PROD_STATUS` VARCHAR(1) NULL,
  PRIMARY KEY (`ID_PROD`),
  INDEX `CATEGORY_FK_idx` (`ID_CAT` ASC),
  CONSTRAINT `CATEGORY_FK`
    FOREIGN KEY (`ID_CAT`)
    REFERENCES `termex`.`CATEGORY` (`ID_CAT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `termex`.`PRODUCT_DETAIL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `termex`.`PRODUCT_DETAIL` (
  `ID_LANG` INT NOT NULL,
  `ID_PROD` INT NOT NULL,
  `PRODD_DESCRIPTION` VARCHAR(500) NULL,
  INDEX `PRODD_LANG_FK_idx` (`ID_LANG` ASC),
  INDEX `PRODD_PROD_FK_idx` (`ID_PROD` ASC),
  PRIMARY KEY (`ID_LANG`, `ID_PROD`),
  CONSTRAINT `PRODD_LANG_FK`
    FOREIGN KEY (`ID_LANG`)
    REFERENCES `termex`.`LANGUAGE` (`ID_LANG`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PRODD_PROD_FK`
    FOREIGN KEY (`ID_PROD`)
    REFERENCES `termex`.`PRODUCT` (`ID_PROD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `termex`.`BANNER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `termex`.`BANNER` (
  `ID_BAN` INT NOT NULL AUTO_INCREMENT,
  `BAN_STATUS` VARCHAR(1) NULL,
  `BAN_IMG` MEDIUMBLOB NULL,
  `BAN_CREATED_DATE` DATETIME NULL,
  PRIMARY KEY (`ID_BAN`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `termex`.`BANNER_DETAIL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `termex`.`BANNER_DETAIL` (
  `ID_BAN` INT NOT NULL,
  `ID_LANG` INT NOT NULL,
  `BAND_TITLE` VARCHAR(50) NULL,
  INDEX `ID_BAN_idx` (`ID_BAN` ASC),
  INDEX `BANNER_LANG_FK_idx` (`ID_LANG` ASC),
  PRIMARY KEY (`ID_BAN`, `ID_LANG`),
  CONSTRAINT `BANNERD_BAN_FK`
    FOREIGN KEY (`ID_BAN`)
    REFERENCES `termex`.`BANNER` (`ID_BAN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `BANNERD_LANG_FK`
    FOREIGN KEY (`ID_LANG`)
    REFERENCES `termex`.`LANGUAGE` (`ID_LANG`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `termex`.`CATEGORY_DETAIL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `termex`.`CATEGORY_DETAIL` (
  `ID_CAT` INT NOT NULL,
  `ID_LANG` INT NOT NULL,
  `CATD_DESCRIPTION` VARCHAR(500) NULL,
  INDEX `CATD_LANG_FK_idx` (`ID_LANG` ASC),
  INDEX `CATD_CAT_FK_idx` (`ID_CAT` ASC),
  PRIMARY KEY (`ID_CAT`, `ID_LANG`),
  CONSTRAINT `CATD_LANG_FK`
    FOREIGN KEY (`ID_LANG`)
    REFERENCES `termex`.`LANGUAGE` (`ID_LANG`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CATD_CAT_FK`
    FOREIGN KEY (`ID_CAT`)
    REFERENCES `termex`.`CATEGORY` (`ID_CAT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
